# Generated by Django 5.1.6 on 2025-02-15 16:51

import utils.generate_api_id
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecModel',
            fields=[
                ('api_spec_id', models.CharField(default=utils.generate_api_id.spec_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role_type', models.CharField(max_length=255)),
            ],
        ),
    ]
