# Generated by Django 5.1.6 on 2025-02-15 16:56

from django.db import migrations, models

import requests

from utils.blizzard_api.authorize import AuthToBlizzard
from utils.generate_api_id import GenerateApiId

def forwards_func(apps, schema_editor):
    SpecModel = apps.get_model("spec", "SpecModel")
    db_alias = schema_editor.connection.alias
    res_spec_list = requests.get(
        "https://eu.api.blizzard.com/data/wow/playable-specialization/index?namespace=static-eu&locale=de_DE",
        headers={
            "Authorization": f"Bearer {AuthToBlizzard().get_token()}",
        },
    )
    
    specs = []
    
    for spec in res_spec_list.json()["character_specializations"]:
        response = requests.get(
            f"https://eu.api.blizzard.com/data/wow/playable-specialization/{spec["id"]}?namespace=static-eu&locale=de_DE",
            headers={
                "Authorization": f"Bearer {AuthToBlizzard().get_token()}",
            },)
        if response.status_code == 200:
            specs.append(response.json())
            
    if response.status_code == 200:
        spec_list = [
            {
                "api_spec_id": GenerateApiId().generate("spec"),
                "name": single_class["name"],
                "role_type": single_class["role"]["type"],
                "class_id": single_class["playable_class"]["id"],
                
            }
            for single_class in specs
        ]

        SpecModel.objects.using(db_alias).bulk_create(
            [
                SpecModel(
                    api_spec_id=spec_item["api_spec_id"],
                    name=spec_item["name"],
                    role_type=spec_item["role_type"],
                    class_id=spec_item["class_id"],
                )
                for spec_item in spec_list
            ]
        )

def backwards_func(apps, schema_editor):
    SpecModel = apps.get_model("spec", "SpecModel")
    db_alias = schema_editor.connection.alias
    SpecModel.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_classmodel_available_specs"),
        ('spec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specmodel',
            name='class_id',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]
