# Generated by Django 5.1.6 on 2025-02-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0001_initial'),
    ]

    operations = [
    ]
