# Generated by Django 5.1.6 on 2025-02-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0002_fetch_specs'),
        ('spec', '0002_specmodel_class_id'),
    ]

    operations = [
    ]
