# Generated by Django 5.1.6 on 2025-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='api_user_id',
            field=models.CharField(default='user_fcbeea2a-84ba-4ffe-a975-c1b0af906f9e', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
