# Generated by Django 5.1.6 on 2025-02-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customusermodel_api_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='client_token',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='api_user_id',
            field=models.CharField(default='user_2dc306e1-3470-4c4c-81d5-7d4ad99aeab9', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='client_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
