# Generated by Django 5.1.6 on 2025-02-15 15:54

import utils.generate_api_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customusermodel_api_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='api_user_id',
            field=models.CharField(default=utils.generate_api_id.user_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
