# Generated by Django 5.1.6 on 2025-02-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterModel',
            fields=[
                ('api_character_id', models.CharField(default='char_57c7c673-385b-47ca-b062-2db22515df9c', editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField()),
                ('realm', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('faction', models.CharField(max_length=100)),
            ],
        ),
    ]
