# Generated by Django 5.1.6 on 2025-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='api_character_id',
            field=models.CharField(default='char_7373345c-991c-48d1-b3fe-e643533df727', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
