# Generated by Django 5.1.6 on 2025-02-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_alter_charactermodel_api_character_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='api_character_id',
            field=models.CharField(default='char_e77ebfcc-0c7a-4a84-8164-18d6f447cb7b', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
