# Generated by Django 5.1.6 on 2025-02-15 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_charactermodel_api_character_id'),
        ('serverlist', '0004_alter_serverlistmodel_api_server_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='api_character_id',
            field=models.CharField(default='char_0fff8a4a-6764-4142-8302-89f628fce6f7', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='serverlist.serverlistmodel'),
        ),
    ]
