# Generated by Django 5.1.6 on 2025-02-15 15:49

import utils.generate_api_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_charactermodel_api_character_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='api_character_id',
            field=models.CharField(default=utils.generate_api_id.character_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
