# Generated by Django 5.1.6 on 2025-02-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_alter_charactermodel_api_character_id'),
        ('classes', '0003_classmodel_available_specs'),
        ('spec', '0002_specmodel_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactermodel',
            name='class_name',
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='selected_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='classes.classmodel'),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='selected_spec',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='spec.specmodel'),
        ),
    ]
