# Generated by Django 5.1.6 on 2025-02-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_remove_charactermodel_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='faction',
            field=models.CharField(choices=[('Alliance', 'alliance'), ('Horde', 'horde')], default='Alliance', max_length=100),
        ),
    ]
