# Generated by Django 5.1.6 on 2025-02-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_alter_charactermodel_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermodel',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='faction',
            field=models.CharField(choices=[('Allianz', 'alliance'), ('Horde', 'horde')], default='Allianz', max_length=100),
        ),
    ]
