# Generated by Django 5.1.6 on 2025-02-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_charactermodel_is_main_alter_charactermodel_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermodel',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
