# Generated by Django 5.1.6 on 2025-02-15 12:10

from django.db import migrations, models
import requests

from utils.blizzard_api.authorize import AuthToBlizzard
from utils.generate_api_id import GenerateApiId




def forwards_func(apps, schema_editor):
    ServerListModel = apps.get_model("serverlist", "ServerListModel")
    db_alias = schema_editor.connection.alias
    response = requests.get(
        "https://eu.api.blizzard.com/data/wow/realm/index?namespace=dynamic-eu&locale=de_DE",
        headers={
            "Authorization": f"Bearer {AuthToBlizzard().get_token()}",
        },
    )
    print(response.json()["realms"])
    if response.status_code == 200:
        realm_list = [
            {
                "realm_name": realm["name"],
                "realm_id": realm["id"],
                "realm_slug": realm["slug"],
                "realm_region": "EU",
            }
            for realm in response.json()["realms"]
        ]

        ServerListModel.objects.using(db_alias).bulk_create(
            [
                ServerListModel(
                    api_server_list_id=GenerateApiId().generate("seli"),
                    name=realm["realm_name"],
                    blizzard_id=realm["realm_id"],
                    blizzard_slug=realm["realm_slug"],
                    region=realm["realm_region"],
                )
                for realm in realm_list
            ]
        )

            
def backwards_func(apps, schema_editor):
    ServerListModel = apps.get_model("serverlist", "ServerListModel")
    db_alias = schema_editor.connection.alias
    ServerListModel.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerListModel',
            fields=[
                ('api_server_list_id', models.CharField(default='seli_48013022-962f-47c9-83c9-286be251a4af', editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('EU', 'eu'), ('US', 'us'), ('KR', 'kr'), ('TW', 'tw'), ('CN', 'cn')], default='EU', max_length=100)),
                ('blizzard_id', models.IntegerField()),
                ('blizzard_slug', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]
