# Generated by Django 5.1.6 on 2025-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlistmodel',
            name='api_server_list_id',
            field=models.CharField(default='seli_7392551e-4184-4e98-9ca3-479504061dc0', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
