# Generated by Django 5.1.6 on 2025-02-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0002_alter_serverlistmodel_api_server_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlistmodel',
            name='api_server_list_id',
            field=models.CharField(default='seli_23060ab0-f8f6-41c0-ae39-7a6454e1cbed', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
