# Generated by Django 5.1.6 on 2025-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0003_alter_serverlistmodel_api_server_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlistmodel',
            name='api_server_list_id',
            field=models.CharField(default='seli_33b0c40d-06a0-4843-98e0-b60c47780b55', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
