# Generated by Django 5.1.6 on 2025-02-15 15:55

import utils.generate_api_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0004_alter_serverlistmodel_api_server_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlistmodel',
            name='api_server_list_id',
            field=models.CharField(default=utils.generate_api_id.server_list_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
