# Generated by Django 5.1.6 on 2025-02-15 17:51

from django.db import migrations
import requests

from utils.blizzard_api.authorize import AuthToBlizzard
from utils.generate_api_id import GenerateApiId


def forwards_func(apps, schema_editor):
    region_list = ["us"]
    ServerListModel = apps.get_model("serverlist", "ServerListModel")
    db_alias = schema_editor.connection.alias

    for region in region_list:
        response = requests.get(
            f"https://eu.api.blizzard.com/data/wow/realm/index?namespace=dynamic-{region}&locale=de_DE&:region={region}",
            headers={
                "Authorization": f"Bearer {AuthToBlizzard().get_token()}",
            },
        )
        print(response.json())
        if response.status_code == 200:
            realm_list = [
                {
                    "realm_name": realm["name"],
                    "realm_id": realm["id"],
                    "realm_slug": realm["slug"],
                    "realm_region": region.upper(),
                }
                for realm in response.json()["realms"]
            ]

            ServerListModel.objects.using(db_alias).bulk_create(
                [
                    ServerListModel(
                        api_server_list_id=GenerateApiId().generate("seli"),
                        name=realm["realm_name"],
                        blizzard_id=realm["realm_id"],
                        blizzard_slug=realm["realm_slug"],
                        region=realm["realm_region"],
                    )
                    for realm in realm_list
                ]
            )


def backwards_func(apps, schema_editor):
    ServerListModel = apps.get_model("serverlist", "ServerListModel")
    db_alias = schema_editor.connection.alias
    # ServerListModel.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("serverlist", "0005_alter_serverlistmodel_api_server_list_id"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
