# Generated by Django 5.1.6 on 2025-02-16 09:13

import django.db.models.deletion
import utils.generate_api_id
from django.conf import settings
from django.db import migrations, models
import os
import requests

from utils.generate_api_id import GenerateApiId


def forwards_func(apps, schema_editor):
    DiscordAccountModel = apps.get_model("discord_account", "DiscordAccountModel")
    db_alias = schema_editor.connection.alias

    response = requests.get(
        f"https://raid-helper.dev/api/v2/servers/{os.getenv("DISCORD_SERVER_ID", "")}/attendance",
        headers={
            "Authorization": os.getenv("RAID_HELPER_API_KEY", ""),
        },
    )
    print(response.json()["result"])
    if response.status_code == 200:
        discord_account_list = [
            {
                "name": discord_account.get("name", "<unknown>"),
                "accId": discord_account["id"],
                "attended": discord_account["attended"],
                "percentage": discord_account["percentage"],
            }
            for discord_account in response.json()["result"]
        ]

        DiscordAccountModel.objects.using(db_alias).bulk_create(
            [
                DiscordAccountModel(
                    api_discord_acc_id=GenerateApiId().generate("diac"),
                    name=discord_account["name"],
                    accId=discord_account["accId"],
                    attended=discord_account["attended"],
                    percentage=discord_account["percentage"],
                )
                for discord_account in discord_account_list
            ]
        )


def backwards_func(apps, schema_editor):
    DiscordAccountModel = apps.get_model("discord_account", "DiscordAccountModel")
    db_alias = schema_editor.connection.alias
    DiscordAccountModel.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0009_charactermodel_is_internal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordAccountModel",
            fields=[
                (
                    "api_discord_acc_id",
                    models.CharField(
                        default=utils.generate_api_id.discord_acc_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("accId", models.BigIntegerField(default=0, unique=True)),
                ("name", models.CharField(default="", max_length=255)),
                ("attended", models.BigIntegerField(default=0)),
                ("percentage", models.FloatField(default=0.0)),
                (
                    "connected_characters",
                    models.ManyToManyField(
                        related_name="characters", to="character.charactermodel"
                    ),
                ),
                (
                    "connected_user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]
