# Generated by Django 5.1.6 on 2025-02-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_charactermodel_is_internal'),
        ('discord_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordaccountmodel',
            name='connected_characters',
            field=models.ManyToManyField(blank=True, related_name='characters', to='character.charactermodel'),
        ),
    ]
