# Generated by Django 5.1.6 on 2025-02-15 16:23

from django.db import migrations


import requests

from utils.blizzard_api.authorize import AuthToBlizzard
from utils.generate_api_id import GenerateApiId




def forwards_func(apps, schema_editor):
    ClassModel = apps.get_model("classes", "ClassModel")
    db_alias = schema_editor.connection.alias
    response = requests.get(
        "https://eu.api.blizzard.com/data/wow/playable-class/index?namespace=static-eu&locale=de_DE",
        headers={
            "Authorization": f"Bearer {AuthToBlizzard().get_token()}",
        },
    )
    print(response.json()["classes"])
    if response.status_code == 200:
        class_list = [
            {
                "api_class_id": GenerateApiId().generate("class"),
                "class_name": single_class["name"],
                "class_id": single_class["id"],
            }
            for single_class in response.json()["classes"]
        ]

        ClassModel.objects.using(db_alias).bulk_create(
            [
                ClassModel(
                    api_class_id=class_item["api_class_id"],
                    name=class_item["class_name"],
                    class_id=class_item["class_id"],
                )
                for class_item in class_list
            ]
        )

            
def backwards_func(apps, schema_editor):
    ClassModel = apps.get_model("classes", "ClassModel")
    db_alias = schema_editor.connection.alias
    ClassModel.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
