# Generated by Django 5.1.6 on 2025-02-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_fetch_classes'),
        ('spec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='available_specs',
            field=models.ManyToManyField(related_name='classes', to='spec.specmodel'),
        ),
    ]
